id: PROJ_2024_009
nom_projet: Atelier de réparation Picard
ref_administrative: ""
promoteur: SARL Picard & Fils
adresse: Zone industrielle, Fès
coordonnees_gps:
  latitude: 0.0
  longitude: 0.0
statut: livre
etape_actuelle: Clôture administrative
derniere_mise_a_jour: "2025-03-20T08:00:00Z"