id: PROJ_2026_005
nom_projet: Complexe Atlassia
ref_administrative: Permis de construire n° 2026/0322/AGD
promoteur: Groupe Atlassia Développement
adresse: Boulevard du 20 Août, Agadir
coordonnees_gps:
  latitude: 30.4278
  longitude: -9.5981
statut: finalise
etape_actuelle: Réception des travaux
derniere_mise_a_jour: '2026-09-10T10:00:00Z'
