id: PROJ_2026_002
nom_projet: Résidence Oasis
ref_administrative: ''
promoteur: ''
adresse: ''
coordonnees_gps:
  latitude: 0.0
  longitude: 0.0
statut: devis
etape_actuelle: Étude architecturale
derniere_mise_a_jour: '2026-09-10T10:00:00Z'
