id: PLANMASSE_ZAMOIMMO_2
nom_projet: REALISATION D’UN LOTISSEMENT AL BOUCHRA YF
ref_administrative: ''
promoteur: MINISTRE DES HABOUS ET AFFAIRES ISLAMIQUES ET SOCIETE
adresse: Rue Mansour Dahbi, immeuble
coordonnees_gps:
  latitude: 0.0
  longitude: 0.0
statut: devis
etape_actuelle: ''
derniere_mise_a_jour: '2026-09-11T13:37:03.817672Z'
